import Link from "next/link";
import { ArrowLeft, ShieldAlert, FileText } from "lucide-react";

export const metadata = {
  title: "Terms and Conditions - WhereIsMyPhoto",
  description: "Terms of Service, acceptable use policy, and strict anti-stalking rules for WhereIsMyPhoto.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-zinc-900 flex flex-col">
      <header className="border-b border-zinc-200 bg-white/95 sticky top-0 z-40 backdrop-blur">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-zinc-600 hover:text-zinc-950 transition-colors font-medium"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Search Engine</span>
          </Link>
          <span className="font-title text-xl font-bold tracking-tight text-zinc-950">
            WhereIsMyPhoto
          </span>
        </div>
      </header>

      <main className="max-w-4xl w-full mx-auto px-6 py-12 space-y-10">
        <div className="space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-100 border border-zinc-300 text-xs text-zinc-700">
            <FileText className="h-3.5 w-3.5" />
            <span>Legal Agreement & Acceptable Use</span>
          </div>
          <h1 className="font-title text-4xl sm:text-5xl font-bold text-zinc-950 tracking-tight">
            Terms of Service & Acceptable Use
          </h1>
          <p className="text-sm text-zinc-500">
            Last Updated: September 2026
          </p>
        </div>

        {/* Anti-Stalking Warning Box */}
        <div className="p-6 rounded-2xl bg-red-50/70 border-2 border-red-200 space-y-3">
          <div className="flex items-center gap-2.5 text-red-800 font-semibold text-base">
            <ShieldAlert className="h-5 w-5 flex-shrink-0 text-red-700" />
            <span>STRICT ANTI-STALKING & ETHICAL USAGE CLAUSE</span>
          </div>
          <p className="text-sm text-zinc-800 leading-relaxed">
            WhereIsMyPhoto is designed strictly as an <strong>image reverse search and digital footprint audit tool</strong> to help individuals and creators discover where their own photos appear on the public web.
          </p>
          <p className="text-sm text-zinc-800 leading-relaxed">
            You are <strong>STRICTLY PROHIBITED</strong> from using this service for:
          </p>
          <ul className="list-disc list-inside text-sm text-zinc-700 space-y-1 pl-2">
            <li>Stalking, tracking, harassing, or intimidating any individual.</li>
            <li>Conducting non-consensual surveillance or doxxing individuals.</li>
            <li>Identifying strangers without explicit authorization.</li>
            <li>Circumventing protective orders, privacy settings, or court injunctions.</li>
          </ul>
          <p className="text-xs text-zinc-500 pt-1">
            Violations of these terms may result in immediate access termination, IP blacklisting, and reporting to relevant legal authorities.
          </p>
        </div>

        <section className="space-y-4 text-sm text-zinc-700 leading-relaxed">
          <h2 className="font-title text-2xl font-bold text-zinc-950">
            1. Nature of the Service
          </h2>
          <p>
            WhereIsMyPhoto operates purely as a visual search indexer. It does not maintain a personal identification registry or private database of identities. It queries public internet records to return public URLs containing visual matches.
          </p>
        </section>

        <section className="space-y-4 text-sm text-zinc-700 leading-relaxed">
          <h2 className="font-title text-2xl font-bold text-zinc-950">
            2. Intellectual Property & Privacy Rights
          </h2>
          <p>
            You affirm that you have the legal right or consent to search the uploaded image. We do not claim ownership of uploaded images and process them in transient memory solely for hashing, feature extraction, and real-time public querying.
          </p>
        </section>

        <section className="space-y-4 text-sm text-zinc-700 leading-relaxed">
          <h2 className="font-title text-2xl font-bold text-zinc-950">
            3. Blockchain Verification Disclaimer
          </h2>
          <p>
            Cryptographic attestations (SHA-256 and Merkle proofs) generated by this system represent immutable digital fingerprints of search results at a given timestamp. They do not constitute a legal subpoena or government certification of identity.
          </p>
        </section>

        <section className="space-y-4 text-sm text-zinc-700 leading-relaxed">
          <h2 className="font-title text-2xl font-bold text-zinc-950">
            4. Limitation of Liability
          </h2>
          <p>
            WhereIsMyPhoto and its developers provide this open technology platform "as is" without warranty. We are not liable for third-party content indexed from external websites or social platforms.
          </p>
        </section>
      </main>

      <footer className="border-t border-zinc-200 bg-zinc-50 py-8 text-center text-xs text-zinc-500 mt-auto">
        <p>WhereIsMyPhoto • Committed to ethical image search and privacy protection</p>
      </footer>
    </div>
  );
}
